### PR TITLE
Text edits

### PR DESCRIPTION
**Pull request by betatim**
These are my text edits for the notebook.

Tried to make one commit per section to allow for slightly easier to read diffs. `git diff --word-diff` is quite good.

I have not got to the end of the notebook yet, so I will add a few more commits later today.

(If it isn't easier to read or happy I can squash all these into one commit)

### CODE REVIEW

**Comment by glouppe** [comment]
Thanks Tim! This is all good to me, dont worry about the diffs :)

**Comment by glouppe** [comment]
(Tell me when I should merge this)

**Comment by glouppe** [comment]
toaccidentally -> to accidentally

**Comment by glouppe** [comment]
In High Energy Physics classifiers are often train => trained?

**Comment by betatim** [comment]
Done.

**Comment by glouppe** [comment]
Thanks a lot, merging

**Pull request merged**
